Tip: hit shift-enter after each Python statement to run it

Import Pandas for data parsing

SciKit Learn is the machine learning framework

In [11]:
import pandas
import numpy as np
from sklearn import svm

Read data from csv file. Just print "raw_data" to see what is inside.

Q: Can you spot the relationship between a number and the class?

In [2]:
raw_data = pandas.read_csv('/rodata/exercise01/part1.csv', \
                           index_col=None)

In [3]:
raw_data.head(5)

number  class
0      23      0
1      54      1
2      36      0
3      60      1
4      62      1

In [4]:
raw_data.shape

(1000, 2)

raw_data has a number and a class. The goal is that our ML can learn the class for the numbers.

For that, we need to split them. Class goes into one array, the data to learn (a.k.a. "features" in another)

In [5]:
learn_data = raw_data.copy()
classes = raw_data['class']
del learn_data['class']

We use a Support Vector Classifier

In [41]:
classifier = svm.SVC(kernel= 'linear', C=float('inf'))

Tell the classifier to learn based on reference data

In [42]:
classifier.fit(learn_data.values, classes)

SVC(C=inf, kernel='linear')

Now we can see if the system has learned something

In [8]:
classifier.predict([[99,]])

array([1])

Q: How good are the predictions of numbers between 1 and 100? Do they match your finding of the relationship?

Q: What about other numbers (smaller 1 or larger 100)?

In [32]:
# Get accuracy score
classifier.score(learn_data.values, classes) 

1.0

we had a perfect fit for the raw data

In [ ]:
import matplotlib 

In [16]:
# we create sa sample test of numbers between 51 and 100. 
# predictions should all be ones

test = np.arange(51,100,1)
classifier.predict(test.reshape(-1,1))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1])

In [43]:
# how abour out-of -range values?

# we create an aray of negative values
test2 = np.arange(-100,0,1)
classifier.predict(test2.reshape(-1,1))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
# and an array of positive values greter than 100
test3 = np.arange(130,200,1)
classifier.predict(test3.reshape(-1,1))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [ ]:
# the model does no predict well for values above 135

In [38]:
from sklearn.model_selection import train_test_split

# a different approach is to split data into trining and test

# Split data into training and test set
features_train, features_test, target_train, target_test = train_test_split(
    learn_data.values, classes, test_size=0.2, random_state=7)

# we run the model again
classifier.fit(features_train, target_train)

# and then we test it with the test set:
classifier.score(features_test, target_test)


1.0